# SPDX-FileCopyrightText: 2025 Blender Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

# This is the OpenAPI specification for Blender's Remote Assets system.
#
# It has been intentionally trimmed down to the bare minimum for a review of the
# code generator in general, and how it integrates into Blender's build system.
#
# The `paths` section is not used by the Blender code, and is here just for
# referencing by humans. The Python code generator just uses the data structures
# specified by the `components` section.

openapi: 3.0.0
info:
  version: 1.0.0
  title: Blender Asset Library API
  description: Blender's API for describing and fetching assets from online libraries.
  contact:
    name: Blender
    url: https://www.blender.org/
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: /
paths:
  /_asset-library-meta.json:
    summary: Meta-information about this asset library.
    get:
      summary: Retrieve the asset library meta info.
      operationId: getLibraryMeta
      responses:
        "200":
          description: normal response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetLibraryMeta"

  /_v1/asset-index.json:
    summary: The index of the asset library, containing the metadata of all available assets.
    get:
      summary: Get the asset library index.
      operationId: getLibraryIndex
      responses:
        "200":
          description: normal response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssetLibraryIndexV1"

components:
  schemas:

    AssetLibraryMeta:
      type: object
      description: "Meta-data of this asset library."
      properties:
        "name":
          type: string
          description: Name of this asset library.
        "contact": { $ref: "#/components/schemas/Contact" }
      required: [api_versions, name, contact]
      example:
        name: Blender Essentials
        contact:
          name: Blender
          url: https://www.blender.org/

    Contact:
      type: object
      description: Owner / publisher of this asset library.
      properties:
        "name": { type: string }
        "url": { type: string }
        "email": { type: string }
      required: [name]
